!
! $Header: /home/cvsroot/LMDZ4/libf/phylmd/YOECUMF.h,v 1.1.1.1 2004/05/19 12:53:07 lmdzadmin Exp $
!
C     ----------------------------------------------------------------
C*    *COMMON* *YOECUMF* - PARAMETERS FOR CUMULUS MASSFLUX SCHEME
C     ----------------------------------------------------------------
C
      COMMON /YOECUMF/
     L                 LMFPEN,LMFSCV,LMFMID,LMFDD,LMFDUDV,
     R                 ENTRPEN,ENTRSCV,ENTRMID,ENTRDD,CMFCTOP,
     R                 CMFCMAX,CMFCMIN,CMFDEPS,RHCDD,CPRCON
C
      LOGICAL          LMFPEN,LMFSCV,LMFMID,LMFDD,LMFDUDV
      REAL ENTRPEN, ENTRSCV, ENTRMID, ENTRDD
      REAL CMFCTOP, CMFCMAX, CMFCMIN, CMFDEPS, RHCDD, CPRCON
C
*if (DOC,declared) <> 'UNKNOWN'
C*    *COMMON* *YOECUMF* - PARAMETERS FOR CUMULUS MASSFLUX SCHEME
C
C     M.TIEDTKE       E. C. M. W. F.      18/1/89
C
C     NAME      TYPE      PURPOSE
C     ----      ----      -------
C
C     LMFPEN    LOGICAL  TRUE IF PENETRATIVE CONVECTION IS SWITCHED ON
C     LMFSCV    LOGICAL  TRUE IF SHALLOW     CONVECTION IS SWITCHED ON
C     LMFMID    LOGICAL  TRUE IF MIDLEVEL    CONVECTION IS SWITCHED ON
C     LMFDD     LOGICAL  TRUE IF CUMULUS DOWNDRAFT      IS SWITCHED ON
C     LMFDUDV   LOGICAL  TRUE IF CUMULUS FRICTION       IS SWITCHED ON
C     ENTRPEN   REAL     ENTRAINMENT RATE FOR PENETRATIVE CONVECTION
C     ENTRSCV   REAL     ENTRAINMENT RATE FOR SHALLOW CONVECTION
C     ENTRMID   REAL     ENTRAINMENT RATE FOR MIDLEVEL CONVECTION
C     ENTRDD    REAL     ENTRAINMENT RATE FOR CUMULUS DOWNDRAFTS
C     CMFCTOP   REAL     RELAT. CLOUD MASSFLUX AT LEVEL ABOVE NONBUOYANC
C     CMFCMAX   REAL     MAXIMUM MASSFLUX VALUE ALLOWED FOR
C     CMFCMIN   REAL     MINIMUM MASSFLUX VALUE (FOR SAFETY)
C     CMFDEPS   REAL     FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
C     RHCDD     REAL     RELATIVE SATURATION IN DOWNDRAFTS
C     CPRCON    REAL     COEFFICIENTS FOR DETERMINING CONVERSION
C                        FROM CLOUD WATER TO RAIN
*ifend
C     ----------------------------------------------------------------
