module yoethf

  ! From phylmd/yoethf.inc,v 1.1.1.1 2004/05/19 12:53:09
  ! DERIVED CONSTANTS SPECIFIC TO ECMWF THERMODYNAMICS

  implicit none

  REAL R2ES, R3LES, R3IES, R4LES, R4IES, R5LES, R5IES
  ! CONSTANTS USED FOR COMPUTATION OF SATURATION MIXING RATIO OVER
  ! LIQUID WATER (R_LES) OR ICE (R_IES)

  REAL RVTMP2 ! RCPV / RCPD - 1.
  real RHOH2O ! DENSITY OF LIQUID WATER (RATM / 100.)

  save

end module yoethf
