module yoecumf

  ! From phylmd/YOECUMF.h, version 1.1.1.1 2004/05/19 12:53:07

  ! M. Tiedtke, E. C. M. W. F., 18th Jan. 1989
  ! Parameters for cumulus massflux scheme

  implicit none

  LOGICAL LMFPEN ! PENETRATIVE CONVECTION SWITCHED ON
  logical LMFSCV ! SHALLOW CONVECTION SWITCHED ON
  logical LMFMID ! MIDLEVEL CONVECTION SWITCHED ON
  logical LMFDD ! CUMULUS DOWNDRAFT SWITCHED ON
  logical LMFDUDV ! CUMULUS FRICTION SWITCHED ON
  REAL ENTRPEN ! ENTRAINMENT RATE FOR PENETRATIVE CONVECTION
  real ENTRSCV ! ENTRAINMENT RATE FOR SHALLOW CONVECTION
  real ENTRMID ! ENTRAINMENT RATE FOR MIDLEVEL CONVECTION
  real ENTRDD ! ENTRAINMENT RATE FOR CUMULUS DOWNDRAFTS
  REAL CMFCTOP ! RELAT. CLOUD MASSFLUX AT LEVEL ABOVE NONBUOYANC
  real CMFCMAX ! MAXIMUM MASSFLUX VALUE ALLOWED FOR
  real CMFCMIN ! MINIMUM MASSFLUX VALUE (FOR SAFETY)
  real CMFDEPS ! FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
  real RHCDD ! RELATIVE SATURATION IN DOWNDRAFTS
  real CPRCON ! COEFFICIENTS FOR DETERMINING CONVERSION FROM CLOUD WATER TO RAIN

contains

  SUBROUTINE flxsetup

    ! This routine defines disposable parameters for massflux scheme.

    !--------------------------------------------------------

    ENTRPEN = 1E-4 ! ENTRAINMENT RATE FOR PENETRATIVE CONVECTION
    ENTRSCV = 3E-4 ! ENTRAINMENT RATE FOR SHALLOW CONVECTION
    ENTRMID = 1E-4 ! ENTRAINMENT RATE FOR MIDLEVEL CONVECTION
    ENTRDD = 2E-4 ! ENTRAINMENT RATE FOR DOWNDRAFTS
    CMFCTOP = 0.33 ! RELATIVE CLOUD MASSFLUX AT LEVEL ABOVE NONBUO LEVEL
    CMFCMAX = 1. ! MAXIMUM MASSFLUX VALUE ALLOWED FOR UPDRAFTS ETC
    CMFCMIN = 1E-10 ! MINIMUM MASSFLUX VALUE (FOR SAFETY)
    CMFDEPS = 0.3 ! FRACTIONAL MASSFLUX FOR DOWNDRAFTS AT LFS
    CPRCON = 2E-4 ! CONVERSION FROM CLOUD WATER TO RAIN

    RHCDD = 1.
    ! RELATIVE SATURATION IN DOWNDRAFtS (NO LONGER USED) (FORMULATION
    ! IMPLIES SATURATION)

    LMFPEN = .TRUE.
    LMFSCV = .TRUE.
    LMFMID = .TRUE.
    LMFDD = .TRUE.
    LMFDUDV = .TRUE.

  END SUBROUTINE flxsetup

end module yoecumf
